# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import block_chain_pb2 as block__chain__pb2
import common_pb2 as common__pb2


class BlockChainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhisperAuditRequest = channel.unary_unary(
                '/blockchain.BlockChainService/WhisperAuditRequest',
                request_serializer=common__pb2.FileAudit.SerializeToString,
                response_deserializer=block__chain__pb2.WhisperResponse.FromString,
                )
        self.ProposeBlock = channel.unary_unary(
                '/blockchain.BlockChainService/ProposeBlock',
                request_serializer=block__chain__pb2.Block.SerializeToString,
                response_deserializer=block__chain__pb2.BlockVoteResponse.FromString,
                )
        self.CommitBlock = channel.unary_unary(
                '/blockchain.BlockChainService/CommitBlock',
                request_serializer=block__chain__pb2.Block.SerializeToString,
                response_deserializer=block__chain__pb2.BlockCommitResponse.FromString,
                )
        self.GetBlock = channel.unary_unary(
                '/blockchain.BlockChainService/GetBlock',
                request_serializer=block__chain__pb2.GetBlockRequest.SerializeToString,
                response_deserializer=block__chain__pb2.GetBlockResponse.FromString,
                )
        self.SendHeartbeat = channel.unary_unary(
                '/blockchain.BlockChainService/SendHeartbeat',
                request_serializer=block__chain__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=block__chain__pb2.HeartbeatResponse.FromString,
                )
        self.TriggerElection = channel.unary_unary(
                '/blockchain.BlockChainService/TriggerElection',
                request_serializer=block__chain__pb2.TriggerElectionRequest.SerializeToString,
                response_deserializer=block__chain__pb2.TriggerElectionResponse.FromString,
                )
        self.NotifyLeadership = channel.unary_unary(
                '/blockchain.BlockChainService/NotifyLeadership',
                request_serializer=block__chain__pb2.NotifyLeadershipRequest.SerializeToString,
                response_deserializer=block__chain__pb2.NotifyLeadershipResponse.FromString,
                )


class BlockChainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WhisperAuditRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyLeadership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockChainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhisperAuditRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.WhisperAuditRequest,
                    request_deserializer=common__pb2.FileAudit.FromString,
                    response_serializer=block__chain__pb2.WhisperResponse.SerializeToString,
            ),
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=block__chain__pb2.Block.FromString,
                    response_serializer=block__chain__pb2.BlockVoteResponse.SerializeToString,
            ),
            'CommitBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitBlock,
                    request_deserializer=block__chain__pb2.Block.FromString,
                    response_serializer=block__chain__pb2.BlockCommitResponse.SerializeToString,
            ),
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=block__chain__pb2.GetBlockRequest.FromString,
                    response_serializer=block__chain__pb2.GetBlockResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=block__chain__pb2.HeartbeatRequest.FromString,
                    response_serializer=block__chain__pb2.HeartbeatResponse.SerializeToString,
            ),
            'TriggerElection': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerElection,
                    request_deserializer=block__chain__pb2.TriggerElectionRequest.FromString,
                    response_serializer=block__chain__pb2.TriggerElectionResponse.SerializeToString,
            ),
            'NotifyLeadership': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyLeadership,
                    request_deserializer=block__chain__pb2.NotifyLeadershipRequest.FromString,
                    response_serializer=block__chain__pb2.NotifyLeadershipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockChainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlockChainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WhisperAuditRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/WhisperAuditRequest',
            common__pb2.FileAudit.SerializeToString,
            block__chain__pb2.WhisperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/ProposeBlock',
            block__chain__pb2.Block.SerializeToString,
            block__chain__pb2.BlockVoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/CommitBlock',
            block__chain__pb2.Block.SerializeToString,
            block__chain__pb2.BlockCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/GetBlock',
            block__chain__pb2.GetBlockRequest.SerializeToString,
            block__chain__pb2.GetBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/SendHeartbeat',
            block__chain__pb2.HeartbeatRequest.SerializeToString,
            block__chain__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/TriggerElection',
            block__chain__pb2.TriggerElectionRequest.SerializeToString,
            block__chain__pb2.TriggerElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyLeadership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockChainService/NotifyLeadership',
            block__chain__pb2.NotifyLeadershipRequest.SerializeToString,
            block__chain__pb2.NotifyLeadershipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
