# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import block_chain_pb2 as block__chain__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in block_chain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockChainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhisperAuditRequest = channel.unary_unary(
                '/blockchain.BlockChainService/WhisperAuditRequest',
                request_serializer=common__pb2.FileAudit.SerializeToString,
                response_deserializer=block__chain__pb2.WhisperResponse.FromString,
                _registered_method=True)
        self.ProposeBlock = channel.unary_unary(
                '/blockchain.BlockChainService/ProposeBlock',
                request_serializer=block__chain__pb2.BlockProposal.SerializeToString,
                response_deserializer=block__chain__pb2.BlockVoteResponse.FromString,
                _registered_method=True)
        self.VoteOnBlock = channel.unary_unary(
                '/blockchain.BlockChainService/VoteOnBlock',
                request_serializer=block__chain__pb2.Vote.SerializeToString,
                response_deserializer=block__chain__pb2.BlockVoteResponse.FromString,
                _registered_method=True)


class BlockChainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WhisperAuditRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteOnBlock(self, request, context):
        """rpc FinalizeBlock ();
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockChainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhisperAuditRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.WhisperAuditRequest,
                    request_deserializer=common__pb2.FileAudit.FromString,
                    response_serializer=block__chain__pb2.WhisperResponse.SerializeToString,
            ),
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=block__chain__pb2.BlockProposal.FromString,
                    response_serializer=block__chain__pb2.BlockVoteResponse.SerializeToString,
            ),
            'VoteOnBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteOnBlock,
                    request_deserializer=block__chain__pb2.Vote.FromString,
                    response_serializer=block__chain__pb2.BlockVoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockChainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blockchain.BlockChainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockChainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WhisperAuditRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockChainService/WhisperAuditRequest',
            common__pb2.FileAudit.SerializeToString,
            block__chain__pb2.WhisperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockChainService/ProposeBlock',
            block__chain__pb2.BlockProposal.SerializeToString,
            block__chain__pb2.BlockVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoteOnBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockChainService/VoteOnBlock',
            block__chain__pb2.Vote.SerializeToString,
            block__chain__pb2.BlockVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
