# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\".\n\x08\x46ileInfo\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\".\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\"\xc8\x01\n\tFileAudit\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12#\n\tfile_info\x18\x02 \x01(\x0b\x32\x10.common.FileInfo\x12#\n\tuser_info\x18\x03 \x01(\x0b\x32\x10.common.UserInfo\x12\'\n\x0b\x61\x63\x63\x65ss_type\x18\x04 \x01(\x0e\x32\x12.common.AccessType\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x11\n\tsignature\x18\x06 \x01(\t\x12\x12\n\npublic_key\x18\x07 \x01(\t*F\n\nAccessType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04READ\x10\x01\x12\t\n\x05WRITE\x10\x02\x12\n\n\x06UPDATE\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCESSTYPE']._serialized_start=323
  _globals['_ACCESSTYPE']._serialized_end=393
  _globals['_FILEINFO']._serialized_start=24
  _globals['_FILEINFO']._serialized_end=70
  _globals['_USERINFO']._serialized_start=72
  _globals['_USERINFO']._serialized_end=118
  _globals['_FILEAUDIT']._serialized_start=121
  _globals['_FILEAUDIT']._serialized_end=321
# @@protoc_insertion_point(module_scope)
