# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_audit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ile_audit.proto\x12\tfileaudit\x1a\x0c\x63ommon.proto\"J\n\x11\x46ileAuditResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2R\n\x10\x46ileAuditService\x12>\n\x0bSubmitAudit\x12\x11.common.FileAudit\x1a\x1c.fileaudit.FileAuditResponseBs\n+com.codecatalyst.auditchain.proto.fileauditB\x0e\x46ileAuditProtoZ4github.com/sameersah/auditchain/proto_gen/file_auditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_audit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.codecatalyst.auditchain.proto.fileauditB\016FileAuditProtoZ4github.com/sameersah/auditchain/proto_gen/file_audit'
  _globals['_FILEAUDITRESPONSE']._serialized_start=45
  _globals['_FILEAUDITRESPONSE']._serialized_end=119
  _globals['_FILEAUDITSERVICE']._serialized_start=121
  _globals['_FILEAUDITSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
