# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_audit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ile_audit.proto\x12\tfileaudit\x1a\x0c\x63ommon.proto\"\x94\x01\n\x11\x46ileAuditResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x1a\n\x12\x62lockchain_tx_hash\x18\x02 \x01(\t\x12,\n\x0c\x62lock_header\x18\x03 \x01(\x0b\x32\x16.fileaudit.BlockHeader\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"\xa8\x01\n\x0b\x42lockHeader\x12\x12\n\nblock_hash\x18\x01 \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x04\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x1b\n\x13previous_block_hash\x18\x04 \x01(\t\x12\x13\n\x0bmerkle_root\x18\x05 \x01(\t\x12\x14\n\x0cmerkle_proof\x18\x06 \x03(\t\x12\x14\n\x0c\x61udit_hashes\x18\x07 \x03(\t2R\n\x10\x46ileAuditService\x12>\n\x0bSubmitAudit\x12\x11.common.FileAudit\x1a\x1c.fileaudit.FileAuditResponseBs\n+com.codecatalyst.auditchain.proto.fileauditB\x0e\x46ileAuditProtoZ4github.com/sameersah/auditchain/proto_gen/file_auditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_audit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.codecatalyst.auditchain.proto.fileauditB\016FileAuditProtoZ4github.com/sameersah/auditchain/proto_gen/file_audit'
  _globals['_FILEAUDITRESPONSE']._serialized_start=46
  _globals['_FILEAUDITRESPONSE']._serialized_end=194
  _globals['_BLOCKHEADER']._serialized_start=197
  _globals['_BLOCKHEADER']._serialized_end=365
  _globals['_FILEAUDITSERVICE']._serialized_start=367
  _globals['_FILEAUDITSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
